### ISSUE TITLE
Contained application immediately exits

### ISSUE THREAD

**Issue by ChadSki** [iceboy233/windows-container#2]
Some applications seem to launch correctly through winc.exe, such as notepad.exe and python.exe. Most, however, immediately exit.

```
$>winc.exe -v -l calc.exe
Enabling verbose mode
Enabling event listener
Application path: C:\WINDOWS\SYSTEM32\calc.exe
Command line: calc.exe
Process created, PID = 12564
Process exited, PID = 12564
All process exited
Process terminated with code 0
```

Any ideas why this is the case? I did some step-through debugging, and everything seems to behave the same for notepad (which works) and calc (which doesn't) except that WaitForSingleObject immediately returns for calc.

**Comment by iceboy233** [comment]
Calc.exe launched correctly here (Windows 8, 64-bit).

You can use [Procmon](http://live.sysinternals.com/Procmon.exe) to see what's going on. If you use a debugger, it should be attached to the target process (calc.exe).

**Comment by ChadSki** [comment]
Hmm, I may have been attempting this on Win10 Tech Preview, where calc.exe actually launches a modern application. Unfortunately I just upgraded my Win8 box to Win10, so I can't go back and attempt to reproduce. (I wouldn't expect this to work with modern apps.)

Limited additional testing shows that Win32 apps (such as Putty) do indeed launch correctly, but .Net apps do not. Is sandboxing .Net apps out of scope? I will also test a DirectX 9 app once I get home later.

**Comment by ChadSki** [comment]
Closing this issue, as windows-container is working as expected -- applications only close when they cannot access resources they need to run. I will need to look into ways to selectively allow read access to the filesystem, but avoid write access.
